name: Python Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install ./[dev]
      - name: Install locally
        run: |
          python3 -m pip install --editable .
      - name: Test with pytest
        run: |
          pytest
      - name: Test demo notebook
        run: |
          pytest --nbmake notebooks/demo.ipynb
